### ISSUE TITLE
nvmrc is right?

### ISSUE THREAD

**Issue by DavideDaniel** [awolden/brakes#100]
nvm use says 4.8.4 but the syntax used isn't being transpiled for that.. what is the last version of node that we are supposed to provide support for?

**Comment by awolden** [comment]
Node 4 is the oldest node version that should be supported by Brakes. Our travisCI is passing node 4 without transpilation. Do you see any specific instances of code that are not supported by Node 4?

**Comment by DavideDaniel** [comment]
Yea, we should close this as the root problem was a consumer inadvertently pulling this into browser code.
