### ISSUE TITLE
Timer is not cleared when called function is succesfull

### ISSUE THREAD

**Issue by PeterSt66** [awolden/brakes#14]
When a call is completed the timer is not cleared. Under high load this leads to a large amount of extra processing and the promise is rejected on timeout (after already being resolved)

**Comment by awolden** [comment]
Thanks for the report!

This issue should be fixed in #15. If this fix seems appropriate, I will release it with version 2.0.2.

**Comment by PeterSt66** [comment]
Thanks, good job on the library, especially the hystrix stats. about the only solid lib i've found matching my crits.
small codereview thingy: in the error catch the timer can also be cleared.
And sry for not giving you a pull request, i've forked because I need the Node 6 Promises and had to remove Bluebird (and thus the promisify(..) callback-supporting code).
