### ISSUE TITLE
Add Cumulative Counts to Hystrix Stream

### ISSUE THREAD

**Issue by SimenB** [awolden/brakes#55]
Currently a rolling count is kept, but not a cumulative one.

It would be great of both were available.

https://github.com/Netflix/Hystrix/wiki/Metrics-and-Monitoring#cumulative-and-rolling-event-counts

**Comment by SimenB** [comment]
@awolden ping :smile:

**Comment by awolden** [comment]
This would be a solid addition! Flagging as a feature request.

**Comment by SimenB** [comment]
Please say here if you work on it, I have it on my TODO list (which is admittedly pretty long ATM).

**Comment by zanuka** [comment]
@awolden any update on this one? keen to assist if no on else is

**Comment by SimenB** [comment]
I haven't gotten to it yet

**Comment by Floix** [comment]
@SimenB @awolden  I worked on that and created a PR, would be great if you guys could review and merge it. I think it is an important enhancement for this lib.

**Comment by awolden** [comment]
Thanks for the contribution @Floix!
