### ISSUE TITLE
Two Hystrix servers

### ISSUE THREAD

**Issue by mazzy89** [awolden/brakes#70]
Why in the `examples/hystrix-example.js` there are two Hystrix servers created? One is not enough?

**Comment by awolden** [comment]
Hey @mazzy89, There are two hystrix servers in that example because I use that example file to test turbine integration. Turbine is an aggregation service that combines multiple hystrix streams into one dashboard: https://github.com/Netflix/Turbine/wiki

**Comment by mazzy89** [comment]
Thank you @awolden for the explanation
