### ISSUE TITLE
Single-arg fat arrow function breaks brakes

### ISSUE THREAD

**Issue by rockympls** [awolden/brakes#83]
Sending a fat arrow function without parens (one arg only) into brakes causes an exception: `TypeError: Cannot read property '1' of null`

It appears to be breaking on the regex in `getFnArgs` in `lib/utils.js`: 

```
/^[function\s]?.*?\(([^)]*)\)/
```

**Comment by rockympls** [comment]
Here's a PR for a potential fix: https://github.com/awolden/brakes/pull/84

**Comment by awolden** [comment]
Thanks for the contribution @rockympls!
